package de.thws.Domain.DomainModels;
import java.time.LocalDateTime;

public class User {
    private Long userId;
    private String username;
    private String email;
    private String passwordHash;
    private final LocalDateTime createdAt;
    private User(Long userId, String username, String email, String passwordHash, LocalDateTime createdAt) {
        this.userId = userId;
        this.username = username;
        this.email = email;
        this.passwordHash = passwordHash;
        this.createdAt = LocalDateTime.now();
    }

    public User(String username, String email, String password){
        this.username= username;
        this.email= email;
        this.passwordHash= hashPassword(password);
        this.createdAt= LocalDateTime.now();
    }
    public Long getUserId() {
        return userId;
    } //Id is gonna be generated by the database(?)
    public String getUsername() {
        return username;
    }
    public String getEmail() {
        return email;
    }
    public String getPasswordHash() {
        return passwordHash;
    }
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }
    public void changePassword(String newPasswordHash){
        this.passwordHash= newPasswordHash;
    }
    public void setEmail(String email) {
        this.email = email;
    }
    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }
    public void setUsername(String username) {
        this.username = username;
    }

    public static User createUser(String username, String email, String password){
        String passwordHash= hashPassword(password);
        LocalDateTime createdAt= LocalDateTime.now();
        return new User(null, username, email, passwordHash, createdAt);
    }
    private static String hashPassword(String password){
        //TODO logic to hash the Password
        return password;
    }
}


